serial:
  x: 17582
  y: 17570
  z: 17631
  n: 17615
  p: 17638
  v: 17607

unit:
  x: [0.1, 'um']
  y: [0.1, 'um']
  z: [0.4, 'um']  # [0.39940625, 'um']
  n: [100, 'deg']  # [99.88, 'deg']
  p: [-100, 'deg']  # [-100.4, 'deg']
  v: [-100, 'deg']  # [-99.87, 'deg']

# Note: anything less than 10 ms is going to slow down the controller!
refresh_interval_ms:
  x: 15  # These used to be 30
  y: 15
  z: 15
  n: 15
  p: 15
  v: 15

geometry:
  # Compare the height of the origin at p=0 and 90 deg.
  #p_radius_um: -12.8e3
  p_radius_um: -13.251e3

  # Define z=0 when the v-bed is 105 mm off of the xy bed
  # z_zero_um: 0 # 105e3

  # The height which it will try to keep the origin at.
  # Note: The focal point of the laser is at around 150 mm off the xy bed.
  # z_default_um: 0 # 150e3

  # The default position of motors that are not currently captured, in units.
  default_pos:
    x: 0
    y: 0
    z: 0
    n: 0  # deg
    p: 0
    v: 0

  # Note: 0deg in N is has the machinery to the -x of the bed:
  #  -90 deg:      0 deg:     90 deg:     180 deg:
  #   ==           (0)           ==        |||||
  #   ==--0         |         0--==          |
  #   ==          |||||          ==         (0)

  # Should an incline of 15 deb be P = +15 deg or -15 deg?
  #  That is, which direction do you prefer to incline, + or - P?
  incline_direction: 1